# Generated by Django 4.2.3 on 2023-07-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("_id", models.IntegerField()),
                ("name", models.CharField(max_length=512)),
                ("age", models.IntegerField(null=True)),
                ("address", models.CharField(max_length=512, null=True)),
                ("salary", models.IntegerField(null=True)),
                ("join_date", models.DateTimeField()),
            ],
        ),
    ]
